debug: false

mongodb:
  dsn: mongodb://root:admin@localhost:27017
  database: kiae

loki:
  endpoint: http://localhost:3100

oidc:
  enabled: false
  endpoint: https://accounts.google.com
  clientID: 4574xxxxxxxxxxxxx.apps.googleusercontent.com
  clientSecret: GOCSPX-9irAxNOxxxxxxxxxxxxxxxxxxxxxx