// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: depend/depend.proto

package depend

import (
	context "context"
	kiae "github.com/kiaedev/kiae/api/kiae"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DependServiceClient is the client API for DependService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DependServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Create(ctx context.Context, in *Depend, opts ...grpc.CallOption) (*Depend, error)
	Update(ctx context.Context, in *Depend, opts ...grpc.CallOption) (*Depend, error)
	Delete(ctx context.Context, in *kiae.IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type dependServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDependServiceClient(cc grpc.ClientConnInterface) DependServiceClient {
	return &dependServiceClient{cc}
}

func (c *dependServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/depend.DependService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependServiceClient) Create(ctx context.Context, in *Depend, opts ...grpc.CallOption) (*Depend, error) {
	out := new(Depend)
	err := c.cc.Invoke(ctx, "/depend.DependService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependServiceClient) Update(ctx context.Context, in *Depend, opts ...grpc.CallOption) (*Depend, error) {
	out := new(Depend)
	err := c.cc.Invoke(ctx, "/depend.DependService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dependServiceClient) Delete(ctx context.Context, in *kiae.IdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/depend.DependService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependServiceServer is the server API for DependService service.
// All implementations must embed UnimplementedDependServiceServer
// for forward compatibility
type DependServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	Create(context.Context, *Depend) (*Depend, error)
	Update(context.Context, *Depend) (*Depend, error)
	Delete(context.Context, *kiae.IdRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDependServiceServer()
}

// UnimplementedDependServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDependServiceServer struct {
}

func (UnimplementedDependServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDependServiceServer) Create(context.Context, *Depend) (*Depend, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDependServiceServer) Update(context.Context, *Depend) (*Depend, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDependServiceServer) Delete(context.Context, *kiae.IdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDependServiceServer) mustEmbedUnimplementedDependServiceServer() {}

// UnsafeDependServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DependServiceServer will
// result in compilation errors.
type UnsafeDependServiceServer interface {
	mustEmbedUnimplementedDependServiceServer()
}

func RegisterDependServiceServer(s grpc.ServiceRegistrar, srv DependServiceServer) {
	s.RegisterService(&DependService_ServiceDesc, srv)
}

func _DependService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depend.DependService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Depend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depend.DependService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependServiceServer).Create(ctx, req.(*Depend))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Depend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depend.DependService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependServiceServer).Update(ctx, req.(*Depend))
	}
	return interceptor(ctx, in, info, handler)
}

func _DependService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(kiae.IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/depend.DependService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependServiceServer).Delete(ctx, req.(*kiae.IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DependService_ServiceDesc is the grpc.ServiceDesc for DependService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DependService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "depend.DependService",
	HandlerType: (*DependServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _DependService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DependService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DependService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DependService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "depend/depend.proto",
}
