apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: zpan
  namespace: default
spec:
  components:
    - name: zpan
      type: cloudapp
      properties:
        image: saltbo/zpan
        ports:
          - 8000
          - 8001
        config: /etc/zpan