apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: zpan
  namespace: default
spec:
  components:
    - name: zpan
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
  workflow:
    steps:
      - name: middleware-mysql-init
        type: mysql-db-init
