apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: kiae-system
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: db
          image: mongo:4.2
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: kiae-system
spec:
  ports:
    - name: db
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb