// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"fmt"
	"github.com/gorilla/mux"
	"github.com/kiaedev/kiae/api/graph"
	"github.com/kiaedev/kiae/internal/app/server/dao"
	"github.com/kiaedev/kiae/internal/app/server/service"
	"github.com/kiaedev/kiae/internal/app/server/watch"
	"github.com/kiaedev/kiae/internal/pkg/kcs"
	"github.com/kiaedev/kiae/pkg/loki"
	"github.com/kiaedev/kiae/pkg/mongoutil"
	"github.com/oam-dev/kubevela-core-api/pkg/generated/client/clientset/versioned"
	versioned2 "github.com/pivotal/kpack/pkg/client/clientset/versioned"
	"github.com/spf13/viper"
	"go.mongodb.org/mongo-driver/mongo"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

// Injectors from wire.go:

func buildInjectors(config *rest.Config) (*Server, error) {
	router := mux.NewRouter()
	database, err := dbConstructor()
	if err != nil {
		return nil, err
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return nil, err
	}
	versionedClientset, err := versioned.NewForConfig(config)
	if err != nil {
		return nil, err
	}
	clientset2, err := versioned2.NewForConfig(config)
	if err != nil {
		return nil, err
	}
	client, err := kcs.CtrRuntimeClient(config)
	if err != nil {
		return nil, err
	}
	kubeClients := &kcs.KubeClients{
		K8sCs:         clientset,
		VelaCs:        versionedClientset,
		KpackCs:       clientset2,
		RuntimeClient: client,
	}
	watcher, err := watch.NewWatcher(kubeClients)
	if err != nil {
		return nil, err
	}
	appPodsService := service.NewAppPodsService(watcher)
	lokiClient, err := lokiConstructor()
	if err != nil {
		return nil, err
	}
	appEventService := service.NewAppEventService(lokiClient)
	resolver := &graph.Resolver{
		AppPodsSvc:   appPodsService,
		AppEventsSvc: appEventService,
	}
	projectDao := dao.NewProject(database)
	appDao := dao.NewApp(database)
	entryDao := dao.NewEntryDao(database)
	routeDao := dao.NewRouteDao(database)
	middlewareInstance := dao.NewMiddlewareInstanceDao(database)
	middlewareClaim := dao.NewMiddlewareClaimDao(database)
	egressDao := dao.NewEgressDao(database)
	appService := service.NewAppService(projectDao, appDao, entryDao, routeDao, middlewareInstance, middlewareClaim, egressDao, clientset, versionedClientset)
	appStatusService := service.NewAppStatusService(client, versionedClientset, appService)
	clusterDao := dao.NewClusterDao(database)
	clusterService := service.NewClusterService(clusterDao)
	egressService := service.NewEgressService(appService, egressDao)
	entryService := service.NewEntryService(appService, entryDao)
	projectImageDao := dao.NewProjectImageDao(database)
	projectImageSvc := service.NewProjectImageSvc(projectDao, projectImageDao, kubeClients)
	imageWatcher := service.NewImageWatcher(projectImageSvc, kubeClients)
	middlewareService := service.NewMiddlewareService(client, clientset, middlewareInstance, middlewareClaim, appService)
	projectService := service.NewProjectService(projectDao)
	providerDao := dao.NewProviderDao(database)
	providerTokenDao := dao.NewProviderTokenDao(database)
	providerService := service.NewProviderService(providerDao, providerTokenDao)
	oauth2 := service.NewOauth2Service(projectService, providerService, providerTokenDao)
	routeService := service.NewRouteService(appService, routeDao)
	serviceSets := &service.ServiceSets{
		AppService:        appService,
		AppPodsService:    appPodsService,
		AppStatusService:  appStatusService,
		AppEventService:   appEventService,
		ClusterService:    clusterService,
		EgressService:     egressService,
		EntryService:      entryService,
		ImageWatcher:      imageWatcher,
		MiddlewareService: middlewareService,
		Oauth2:            oauth2,
		ProjectService:    projectService,
		ProjectImageSvc:   projectImageSvc,
		ProviderService:   providerService,
		RouteService:      routeService,
	}
	server := &Server{
		Router:        router,
		db:            database,
		watcher:       watcher,
		kcs:           kubeClients,
		graphResolver: resolver,
		svcSets:       serviceSets,
	}
	return server, nil
}

// wire.go:

func dbConstructor() (*mongo.Database, error) {
	dbClient, err := mongoutil.New(viper.GetString("dsn"))
	if err != nil {
		return nil, fmt.Errorf("failed opening connection to mysql: %v", err)
	}

	return dbClient.DB.Database("kiae"), nil
}

func lokiConstructor() (*loki.Client, error) {
	return loki.NewLoki("http://localhost:3100"), nil
}
