apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiae
  namespace: kiae-system
  labels:
    app: kiae
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiae
  template:
    metadata:
      labels:
        app: kiae
    spec:
      serviceAccountName: kiae
      containers:
        - name: my-app
          image: ko://github.com/kiaedev/kiae
          imagePullPolicy: Always
          args: [ "server" ]
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: "/etc/kiae/"
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: kiae
