// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: kiae/op_status.proto

package kiae

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpStatus int32

const (
	OpStatus_OP_STATUS_DISABLED OpStatus = 0
	OpStatus_OP_STATUS_ENABLED  OpStatus = 1
)

// Enum value maps for OpStatus.
var (
	OpStatus_name = map[int32]string{
		0: "OP_STATUS_DISABLED",
		1: "OP_STATUS_ENABLED",
	}
	OpStatus_value = map[string]int32{
		"OP_STATUS_DISABLED": 0,
		"OP_STATUS_ENABLED":  1,
	}
)

func (x OpStatus) Enum() *OpStatus {
	p := new(OpStatus)
	*p = x
	return p
}

func (x OpStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_kiae_op_status_proto_enumTypes[0].Descriptor()
}

func (OpStatus) Type() protoreflect.EnumType {
	return &file_kiae_op_status_proto_enumTypes[0]
}

func (x OpStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpStatus.Descriptor instead.
func (OpStatus) EnumDescriptor() ([]byte, []int) {
	return file_kiae_op_status_proto_rawDescGZIP(), []int{0}
}

var File_kiae_op_status_proto protoreflect.FileDescriptor

var file_kiae_op_status_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6b, 0x69, 0x61, 0x65, 0x2f, 0x6f, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6b, 0x69, 0x61, 0x65, 0x2a, 0x39, 0x0a, 0x08,
	0x4f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x4f, 0x50, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x15, 0x0a, 0x11, 0x4f, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x4e,
	0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x69, 0x61, 0x65, 0x64, 0x65, 0x76, 0x2f, 0x6b, 0x69,
	0x61, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6b, 0x69, 0x61, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_kiae_op_status_proto_rawDescOnce sync.Once
	file_kiae_op_status_proto_rawDescData = file_kiae_op_status_proto_rawDesc
)

func file_kiae_op_status_proto_rawDescGZIP() []byte {
	file_kiae_op_status_proto_rawDescOnce.Do(func() {
		file_kiae_op_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_kiae_op_status_proto_rawDescData)
	})
	return file_kiae_op_status_proto_rawDescData
}

var file_kiae_op_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kiae_op_status_proto_goTypes = []interface{}{
	(OpStatus)(0), // 0: kiae.OpStatus
}
var file_kiae_op_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kiae_op_status_proto_init() }
func file_kiae_op_status_proto_init() {
	if File_kiae_op_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kiae_op_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kiae_op_status_proto_goTypes,
		DependencyIndexes: file_kiae_op_status_proto_depIdxs,
		EnumInfos:         file_kiae_op_status_proto_enumTypes,
	}.Build()
	File_kiae_op_status_proto = out.File
	file_kiae_op_status_proto_rawDesc = nil
	file_kiae_op_status_proto_goTypes = nil
	file_kiae_op_status_proto_depIdxs = nil
}
