apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: zpan
  namespace: default
spec:
  components:
    - name: zpan
      type: cloudapp
      properties:
        image: saltbo/zpan
        ports:
          - 8000
          - 8001
        config: /etc/zpan
      traits:
        - type: mysql
          properties:

        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              "/": 8000
  workflow:
    steps:
      - name: middleware-mysql-init
        type: mysql-db-init
