# app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vela-app
spec:
  components:
    - name: kapp
      type: k-webservice
      properties:
        image: oamdev/hello-world
        ports:
          - port: 8080
            appProtocol: http
          - port: 8081
            appProtocol: grpc
        resources:
          requests:
            cpu: 0.5
            memory: 128Mi
          limits:
            cpu: 1
            memory: 256Mi
        configs:
          - filename: abc.yaml
            content: aaa
            mountPath: /dev/null
          - filename: abc2.toml
            content: aaa1
            mountPath: /dev/null
    - name: vvv-vex4-routes
      type: k-route
      properties:
        name: vvv-vex4
        gateways:
          - host: vvv-vex4.dev.kiae.localhost
            name: httpbin-gateway
        routes:
          - directResponse:
              body: ok
              code: 200
            methods:
              - GET
            name: ""
            uri: /v1/books
          - methods:
              - GET
            name: ""
            redirect:
              code: 302
              url:
                path: /v1/books
            uri: /install
          - methods:
              - GET
            name: ""
            forward:
              cors:
                enabled: true
                allowOrigins:
                  - http://localhost:8080
                allowMethods:
                  - GET
              rewrite: {}
            uri: /install
          - name: default