# app.yaml
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vela-app
spec:
  components:
    - name: kapp
      type: k-webservice
      properties:
        image: saltbo/hello-world
        ports:
          - port: 8080
            appProtocol: http
          - port: 8081
            appProtocol: grpc
        resources:
          requests:
            cpu: 0.5
            memory: 128Mi
          limits:
            cpu: 1
            memory: 256Mi
      traits:
        - type: k-sidecar
          properties:
            egress:
              - host: "abc.localhost"
                port: 8080
                protocol: http
                external: true

        - type: k-secret2file
          properties:
            secretName: hello-world
        - type: k-config
          properties:
            configs:
              - filename: abc.yaml
                content: aaa
                mountPath: /etc/hello1/
              - filename: abc2.toml
                content: aaa1
                mountPath: /etc/hello2/
        - type: k-route
          properties:
            name: vvv-vex4
            gateways:
              - host: vvv-vex4.dev.kiae.localhost
                name: httpbin-gateway
            routes:
              - directResponse:
                  body: ok
                  code: 200
                methods:
                  - GET
                name: ""
                uri: /v1/books
              - methods:
                  - GET
                name: ""
                redirect:
                  code: 302
                  url:
                    path: /v1/books
                uri: /install
              - methods:
                  - GET
                name: ""
                forward:
                  cors:
                    enabled: true
                    allowOrigins:
                      - http://localhost:8080
                    allowMethods:
                      - GET
                  rewrite: { }
                uri: /install
              - name: default
    - name: mysql
      type: k-mw-mysqldb
      properties:
        dbname: "test"
        instance: "default"